language: python
sudo: required
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install pylint

script:
  - make test

notifications:
  email: false
